version: '3.7'

networks:
  grpc-network:
    driver: bridge 

services:
  app:    
    container_name: grpc   
    build:
      context: .      
      dockerfile: 'Dockerfile'      
      target: dev
    command: sh -c "npm run dev"
    ports:
      - 50051:50051
    networks:
      - grpc-network        
    env_file:
      - .env
    working_dir: /usr/src/app          
    depends_on:
      - db
  db:
    container_name: mongodb      
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_USERNAME: ${MONGO_USER}
      MONGO_INITDB_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db      
    networks:
      - grpc-network
