version: '3.7'

networks:
  grpc-network:
    driver: bridge 
services:
  svc_user:    
    container_name: service-api   
    build:
      context: .      
      dockerfile: 'Dockerfile'      
      target: dev
    command: sh -c "npm run dev"
    ports:
      - 3333:3333
    networks:
      - grpc-network      
    working_dir: /usr/src/app              