version: '3.7'

networks:
  network-grpc:
    driver: bridge 

services:
  svc_purchase:    
    container_name: service-nix
    build:
      context: .      
      dockerfile: 'Dockerfile'      
      target: dev
    command: sh -c "npm run dev"
    ports:
      - 50051:50051
    networks:
      - network-grpc
    env_file:
      - .env
    working_dir: /usr/src/app          
    depends_on:
      - db_purchase
  db_purchase:
    container_name: mongodb-nix      
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_USERNAME: ${MONGO_USER}
      MONGO_INITDB_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./data/db-purchases:/data/db      
    networks:
      - network-grpc